DROP TABLE IF EXISTS Pokebox.PokeType;
DROP TABLE IF EXISTS Pokebox.PokeOwned;
DROP TABLE IF EXISTS Pokebox.ItemOwned;
DROP TABLE IF EXISTS Pokebox.PokemonType;
DROP TABLE IF EXISTS Pokebox.Pokemon;
DROP TABLE IF EXISTS Pokebox.[User];
DROP TABLE IF EXISTS Pokebox.Item;
DROP TABLE IF EXISTS Pokebox.ItemType;
