CREATE TABLE Pokebox.ItemOwned
(
    ItemOwnedID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    UserID INT NOT NULL FOREIGN KEY
        REFERENCES Pokebox.[User](UserID),
    ItemID INT NOT NULL FOREIGN KEY
        REFERENCES Pokebox.Item(ItemID),
    DatePutInBox DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET())

    UNIQUE(UserID, ItemID)
)